### PR TITLE
Part 1 +2 : Game Start and Start Up Phase 

### PR DESCRIPTION
**Pull request by yabdelkawy**
This PR Request details the implementation of Part 1 and Part 2 of the assignment 

Requirements 
**Part 1**
- Different valid maps can be loaded and their validity is verified (i.e. it is a connected graph, etc.), and invalid maps are gracefully rejected; 
- User can select for 2-5 players. The right number of players is created, a deck with the right number of cards is created; 
- The observers can be turned on/off during the game start phase. 
- This must be implemented in a .cpp/.h file duo named GameEngine.cpp /.h

**Part 2**
- The order of play of the players in the game is determined randomly.
- All territories in the map are randomly assigned to players one by one in a round-robin fashion.
- Players are given a number of initial armies (A), where A is:
If 2 players, A=40
If 3 players, A=35
If 4 players, A=30
If 5 players, A=25
These armies are placed in the reinforcement pool. 
- This must be implemented in a function/method named startupPhase() in the game engine. 
- All territories in the map have been assigned to one and only one player; 
- Players are given a number of armies; 
- All players have all the orders for playing in a turn. This must be implemented in a single .cpp/.h file duo named GameEngine.cpp/.h.

Coding Requirements 
- All data of user-defined class type must be of pointer type.
- In case using smart pointer, the data of user-defined class type must not be all smart pointers.
- All file names and the content of the files must be according to what is given in the description below.
- All different parts must be implemented in their own separate .cpp/.h file duo. All functions’ implementation must be provided in the .cpp file (i.e. no inline functions are allowed).
- All classes must implement a correct copy constructor, assignment operator, and stream insertion operator.
- Memory leaks must be avoided.
- Code must be documented using comments (user-defined classes, methods, free functions, operators).
- If you use third-party libraries that are not available in the labs and require setup/installation, you may not assume to have help using them and you are entirely responsible for their proper installation for grading purposes.

Missing 

- Proper implementation of Observer will be commenced once that code is ready. 

Concerns
- Please check if general memory leaks exist

Notes 
- Testing for GameEngine is still currently underway

### CODE REVIEW

**Comment by johnstonstott** [comment]
image
Getting this when trying to run. Is this expected?

**Comment by yabdelkawy** [comment]
> image
> Getting this when trying to run. Is this expected?

Nope! I've fixed these errors in the latest commits

**Review by felixlapierre — APPROVED** [review]
LGTM

**Review by MaelSemler — APPROVED** [review]
Good job!

**Pull request merged**
